micronaut:
  application:
    name: micronaut-monitoring-sandbox
  server:
    cors:
      enabled: true

  metrics:
    enabled: true
    binders:
      jvm:
        enabled:
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true
    tags:
      - foo: bar

endpoints:
  prometheus:
    sensitive: false

